// packages/backend/src/services/nginx.ts
// ホスト上のnginxを直接設定するパスベースリバースプロキシ
import { writeFile } from 'node:fs/promises';
import { exec } from 'node:child_process';
import { promisify } from 'node:util';
import { existsSync, mkdirSync } from 'node:fs';

const execAsync = promisify(exec);
const IS_MOCK   = process.env.INCUS_MOCK === 'true';
const NGINX_CONF_PATH = process.env.NGINX_CONF_PATH ?? '/etc/nginx/conf.d/portal.conf';

export type ProxyRoute = {
  path:       string;  // 例: /app1
  targetIP:   string;
  targetPort: number;
};

// 全ルートからnginx設定を生成
export function generateNginxConf(routes: ProxyRoute[]): string {
  if (routes.length === 0) {
    return `# Auto-generated by PrivateCloud Portal
server {
    listen 8880;
    server_name _;
    location / {
        return 200 'Private Cloud Portal Proxy - No routes configured';
        add_header Content-Type text/plain;
    }
}
`;
  }

  const locations = routes.map(r => {
    const normalizedPath = r.path.endsWith('/') ? r.path : `${r.path}/`;
    return `
    # ${r.path} → ${r.targetIP}:${r.targetPort}
    location ${r.path} {
        return 301 ${normalizedPath};
    }
    location ${normalizedPath} {
        proxy_pass         http://${r.targetIP}:${r.targetPort}/;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_read_timeout 60s;
    }`;
  }).join('\n');

  return `# Auto-generated by PrivateCloud Portal
# DO NOT EDIT MANUALLY - Generated at ${new Date().toISOString()}
server {
    listen 8880;
    server_name _;
${locations}
}
`;
}

// ホスト上のnginx設定ファイルを書き込み
export async function writeNginxConf(conf: string): Promise<void> {
  if (IS_MOCK) {
    console.log('[nginx mock] writeNginxConf:');
    console.log(conf);
    return;
  }

  // ディレクトリ確認
  const dir = NGINX_CONF_PATH.substring(0, NGINX_CONF_PATH.lastIndexOf('/'));
  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true });
  }

  await writeFile(NGINX_CONF_PATH, conf, 'utf-8');
}

// nginx設定テスト
export async function testNginxConf(): Promise<void> {
  if (IS_MOCK) return;
  await execAsync('nginx -t');
}

// nginxリロード
export async function reloadNginx(): Promise<void> {
  if (IS_MOCK) {
    console.log('[nginx mock] reloadNginx');
    return;
  }
  try {
    await execAsync('nginx -s reload');
  } catch {
    // reload失敗時はstartを試みる
    await execAsync('nginx');
  }
}
